server:
  port: 9002
eureka:
  instance:
    hostname: eureka02  #Eureka服务端的实例名字
  client:
    register-with-eureka: false #表示是否向 Eureka 注册中心注册自己(这个模块 本身是服务器,所以不需要)
    fetch-registry: false #fetch-registry如果为false,则表示自己为注册中心
    service-url:
      defaultZone: http://eureka01:9001/eureka/ #对外提供的注册入口，关联其它的eureka01
