server:
  port: 9005
spring:
  application:
    name: discovery01 #SpringCloud是通过实例名发现服务的
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/ #注册到eureka注册中心
