server:
  port: 9008

spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/ #注册到eureka注册中心

#自定义路由映射
zuul:
  routes:
    discovery-service: /get/**
    invoked-service: /select/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #忽略整个服务，对外提供接口
  ignored-services: city_service