server:
  port: 9008

spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/ #注册到eureka注册中心

#自定义路由映射
zuul:
  routes:
    invoked.service: invoked #服务实例
    invoked.path: /gain/**  #原访问论据：：localhost:9008/invoked/select/city?areaId=1，设置后访问路径：localhost:9008/gain/select/city?areaId=1
  ignored-services: invoked #忽略整个服务，对外提供接口,使用localhost:9008/invoked/select/city?areaId=1不能直接问，只能使用localhost:9008/gain/select/city?areaId=1，对多个访问使用“*”
  prefix: /hjz #设置前缀，访问路径：localhost:9008/hjz/gain/select/city?areaId=1
